### PR TITLE
some textures and renames

### PR DESCRIPTION
**Pull request by tobyplowy**

### CODE REVIEW

**Comment by tobyplowy** [comment]
@lipki you put alot of items in the blocks dir

also always change _ to a space

also things like stone_black for example need to be renamed to Black Stone
and dount forget to capitalize the first leters :D

**Comment by lipki** [comment]
Yes, I hesitated.
But for example, for the "clay ball" icon, it is related to the clay block, that's why I put them together.

**Comment by tobyplowy** [comment]
> But for example, for the "clay ball" icon, it is related to the clay block, that's why I put them together.

Yeh that makes sense but I think it's best to put items in the items folder and blocks in the blocks folder and so on

Also I don't have permission to merge PRs for some repos (this one is one of them)
Can you please ask @CuddleWoozle if I can be an owner
This will make sure I can get the propper prevelages in all future repos and the current ones 
It's less work for you (lipki) and I think I deserve it :)
It's also nice to have on my portfolio :)

**Comment by lipki** [comment]
@CuddleWoozle can read you and answer you directly.

I leave you merge, you should be able to.

**Pull request merged**
