### PR TITLE
Add Old Texture

### PR DESCRIPTION
**Pull request by lipki**
And I have a lot left. a looooooooot !

### CODE REVIEW

**Comment by lipki** [comment]
I'm not sure of the separation into blocks / items.

**Comment by CuddleWoozle** [comment]
Can we make a folder for "Items" and a folder for "Blocks" (and maybe a
third for "Mobs")

It would help with organization later on.  :3  Then everyone just separates
it into one of those three and then further refines what it is afterwards.

**Comment by tobyplowy** [comment]
Yeh making a different category for blocks and items is a good idea :)

**Review by tobyplowy — APPROVED** [review]
I aprove this PR but some textures use technical names (I think this should be avoided)

**Comment by lipki** [comment]
Tell me what you find, I'll fix the rest.

**Comment by lipki** [comment]
You know what, I am merging it, and so we will see the organization of the files.
We will correct the names afterwards.

**Comment by tobyplowy** [comment]
Ok

**Pull request merged**
